# Generated by Django 4.2.6 on 2023-10-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.qa')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.thread')),
            ],
        ),
    ]
