# Generated by Django 4.2.6 on 2023-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
